trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - ApplicationUi

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet publish --configuration $(buildConfiguration)
  workingDirectory: ApplicationApi
  displayName: 'dotnet publish $(buildConfiguration)'