trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - ApplicationUi

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    publishWebProjects: false
    projects: 'ApplicationApi/Azure.CI.CD.Demo.API.Tests/Azure.CI.CD.Demo.API.Tests.csproj'
    publishTestResults: true
  displayName: 'dotnet test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'ApplicationApi/Azure.CI.CD.Demo.API/Azure.CI.CD.Demo.API.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: true
  displayName: 'dotnet publish $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
    ArtifactType: 'Container'
  displayName: Publish Build Artifacts

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'scripts'
    ArtifactType: 'Container'
  displayName: Publish Scripts